search_fields requires a list
search_fields='HotelName' returned this error:

HttpResponseError: () Unknown field 'H' in search field list.
Parameter name: searchFields
Code: 
Message: Unknown field 'H' in search field list.
Parameter name: searchFields

Using search_fields=['HotelName'] soved the error